name: Make Cards
on:
  push:
    branches:
      - master

jobs:

  make-cards:
    runs-on: macos-latest
    steps:

    - name: Checkout master branch
      uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

      # First use Python to build the cards

    - name: Install PyYAML dependency
      run: python3 -m pip install pyyaml

    - name: Install BeautifulSoup
      run: python3 -m pip install beautifulsoup4

    - name: Make cards
      run: python3 ./builder/make_cards.py info/ src/index.html

      # Set up git and check if any files were changed

    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Check if files were modified
      id: checkmod
      run: |
        git add -f src/index.html
        if git status | grep -q modified
        then
          echo "::set-output name=filechanged::yes"
        else
          echo "::set-output name=filechanged::no"
        fi

    - name: Fetch project from master branch
      run: git fetch origin master

    - name: Commit changes to index.html
      if:
        steps.checkmod.outputs.filechanged == 'yes'
      run: git commit -m "Auto update index.html"

    - name: Push changes to master branch
      if:
        steps.checkmod.outputs.filechanged == 'yes'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master

    - name: Update GitHub Pages branch
      run: |
        git subtree split --prefix src -b gh-pages
        git push -f "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" gh-pages:gh-pages
        git branch -D gh-pages
